name: Agent CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v5

      - name: Install uv tool
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hubb
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for api
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fitness_multiagent:${{ github.run_id }}
            ${{ secrets.DOCKER_USERNAME }}/fitness_multiagent:latest

      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fitness_frontend:${{ github.run_id }}
            ${{ secrets.DOCKER_USERNAME }}/fitness_frontend:latest

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' ./helm/charts/api/values.yaml
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' ./helm/charts/frontend/values.yaml

      
      - name: Commit and push changes
        run: |
          git config --global user.email "velatdicleli@gmail.com"
          git config --global user.name "VelatDi"
          git add helm
          git commit -m "Update tag in Helm chart"
          git push
